sudo: requires
services:
- docker

before_install:
- docker build -f Dockerfile.dev -t limar/frontenddev .

script:
- docker run limar/frontenddev env CI=1 npm test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  region: us-east-2
  app: udemy-docker-react
  env: UdemyDockerReact-env
  bucket_name: "elasticbeanstalk-us-east-2-615992251931"
  bucket_path: "udemy-docker-react"
  on:
    repo: limar/docker-react
    branch: master
