version : '3'
services:
  webapp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: limar/frontenddev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: limar/frontendtest
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run test

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: limar/frontend
    ports:
      - "3000:80"





